building with vite
zazuko/SPEX pull request #103
Opened 2024-04-10 09:07 UTC by tpluscode

Replaced webpack with vite:

- reduced bundle size
- made dev env faster
- knock off all current dependabot alerts

2024-04-10 16:25 UTC, ludovicm67 approved these changes
Great idea, looks good from what I can see.

Once it's released, I will try also to see if everything is still in order for the Trifid plugin :)

2024-04-10 19:26 UTC, tpluscode commented
> Once it's released, I will try also to see if everything is still in order for the Trifid plugin :)

Big change is that the default package export is not UMD but ESM. This should work better, with code splitting.
Also, I'm unsure about PWA...

2024-04-15 13:29 UTC, ludovicm67 commented
I added `@vitejs/plugin-vue` as dev dependency, as I was getting the following error:

```
error during build:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@vitejs/plugin-vue' imported from …
```

I also made sure that the lock file includes entries for different architectures for rollup, so that we can build the app using different CPU architectures.

2024-04-15 13:38 UTC, ludovicm67 requested changes
I did more deeper checks, and I think some changes could be great.

> > Once it's released, I will try also to see if everything is still in order for the Trifid plugin :)
> 
> Big change is that the default package export is not UMD but ESM. This should work better, with code splitting. Also, I'm unsure about PWA...

As I can see, it's exporting the UMD mostly like before: in `dist/spex.umd.cjs` (it's now with `.cjs` extension instead of `.js`).

Also, `dist/style.css` is the replacement for `dist/spex.css`.

If we want to rename those files, should we consider a major version instead of a minor one? If not, can we make sure they get the same name as before?

2024-04-16 08:34 UTC, tpluscode commented
> If we want to rename those files, should we consider a major version instead of a minor one? If not, can we make sure they get the same name as before?

For `0.x` versions, minor bump is considered a breaking change.

2024-04-16 08:37 UTC, ludovicm67 approved these changes
Oh yes, you are right, we are still on 0.x.
So a breaking change is that paths are also changing as reported.

LGTM.

2024-04-16 08:41 UTC, tpluscode commented
I mentioned the path changes in the changeset

2024-04-16 08:45 UTC, merged